# Generated by Django 5.1.4 on 2024-12-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='authoer',
            new_name='author',
        ),
    ]
