# Generated by Django 5.1.4 on 2025-01-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_authoer_note_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
