# Generated by Django 5.1.4 on 2025-01-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_logged',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
