app = "backend-restless-waterfall-8217"
primary_region = "ewr"

[deploy]
release_command = "python manage.py collectstatic --noinput && python manage.py migrate --noinput"

[env]
PORT = "8000"
DJANGO_SECRET_KEY = "django-insecure-v@)ms+wk+h)!lo*4(l7v9-fomz!a=i__l%ox+nzgo7#j)ln&4h"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000
min_machines_running = 1
processes = ["app"]

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"

[[mounts]]
source = "sqlite_data"
destination = "/data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
